//Upload
const UPLOAD_FILE = 'UPLOAD_FILE';
const UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST';
const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
const UPLOAD_FILE_FAILURE = 'UPLOAD_FILE_FAILURE';
//Load
const LOAD_FILE = 'LOAD_FILE';
const LOAD_FILE_REQUEST = 'LOAD_FILE_REQUEST';
const LOAD_FILE_SUCCESS = 'LOAD_FILE_SUCCESS';
const LOAD_FILE_FAILURE = 'LOAD_FILE_FAILURE';
//Delete
const DELETE_FILE = 'DELETE_FILE';
const DELETE_FILE_REQUEST = 'DELETE_FILE_REQUEST';
const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS';
const DELETE_FILE_FAILURE = 'DELETE_FILE_FAILURE';
//Reset
const RESET_FILE_STATE = 'RESET_FILE_STATE';

export {
  UPLOAD_FILE,
  UPLOAD_FILE_REQUEST,
  UPLOAD_FILE_SUCCESS,
  UPLOAD_FILE_FAILURE,
  LOAD_FILE,
  LOAD_FILE_REQUEST,
  LOAD_FILE_SUCCESS,
  LOAD_FILE_FAILURE,
  RESET_FILE_STATE,
  DELETE_FILE,
  DELETE_FILE_REQUEST,
  DELETE_FILE_SUCCESS,
  DELETE_FILE_FAILURE
}
