//Update Backlog
const UPDATE_BACKLOG = 'UPDATE_BACKLOG';
const UPDATE_BACKLOG_REQUEST = 'UPDATE_BACKLOG_REQUEST';
const UPDATE_BACKLOG_SUCCESS = 'UPDATE_BACKLOG_SUCCESS';
const UPDATE_BACKLOG_FAILURE = 'UPDATE_BACKLOG_FAILURE';

export {
  UPDATE_BACKLOG,
  UPDATE_BACKLOG_REQUEST,
  UPDATE_BACKLOG_SUCCESS,
  UPDATE_BACKLOG_FAILURE
}
