//Update Backlog
const UPDATE_BACKLOG = 'UPDATE_BACKLOG';
const UPDATE_BACKLOG_REQUEST = 'UPDATE_BACKLOG_REQUEST';
const UPDATE_BACKLOG_SUCCESS = 'UPDATE_BACKLOG_SUCCESS';
const UPDATE_BACKLOG_FAILURE = 'UPDATE_BACKLOG_FAILURE';
//Load Issue from Backlog
const LOAD_ALL_ISSUES_FROM_BACKLOG = 'LOAD_ALL_ISSUES_FROM_BACKLOG';
const LOAD_ALL_ISSUES_FROM_BACKLOG_REQUEST = 'LOAD_ALL_ISSUES_FROM_BACKLOG_REQUEST';
const LOAD_ALL_ISSUES_FROM_BACKLOG_SUCCESS = 'LOAD_ALL_ISSUES_FROM_BACKLOG_SUCCESS';
const LOAD_ALL_ISSUES_FROM_BACKLOG_FAILURE = 'LOAD_ALL_ISSUES_FROM_BACKLOG_FAILURE';
//Reset issue list
const RESET_ISSUE_LIST = 'RESET_ISSUE_LIST';
//Get filter by userID
const GET_FILTER = 'GET_FILTER';
const GET_FILTER_REQUEST = 'GET_FILTER_REQUEST';
const GET_FILTER_SUCCESS = 'GET_FILTER_SUCCESS';
const GET_FILTER_FAILURE = 'GET_FILTER_FAILURE';
//update filter
const UPDATE_FILTER = 'UPDATE_FILTER';
const UPDATE_FILTER_REQUEST = 'UPDATE_FILTER_REQUEST';
const UPDATE_FILTER_SUCCESS = 'UPDATE_FILTER_SUCCESS';
const UPDATE_FILTER_FAILURE = 'UPDATE_FILTER_FAILURE';

export {
  GET_FILTER,
  GET_FILTER_REQUEST,
  GET_FILTER_SUCCESS,
  GET_FILTER_FAILURE,
  UPDATE_BACKLOG,
  UPDATE_BACKLOG_REQUEST,
  UPDATE_BACKLOG_SUCCESS,
  UPDATE_BACKLOG_FAILURE,
  LOAD_ALL_ISSUES_FROM_BACKLOG,
  LOAD_ALL_ISSUES_FROM_BACKLOG_REQUEST,
  LOAD_ALL_ISSUES_FROM_BACKLOG_SUCCESS,
  LOAD_ALL_ISSUES_FROM_BACKLOG_FAILURE,
  UPDATE_FILTER,
  UPDATE_FILTER_REQUEST,
  UPDATE_FILTER_SUCCESS,
  UPDATE_FILTER_FAILURE,
  RESET_ISSUE_LIST
}
