//Create message
const CREATE_MESSAGE = 'CREATE_MESSAGE';
const CREATE_MESSAGE_REQUEST = 'CREATE_MESSAGE_REQUEST';
const CREATE_MESSAGE_SUCCESS = 'CREATE_MESSAGE_SUCCESS';
const CREATE_MESSAGE_FAILURE = 'CREATE_MESSAGE_FAILURE';
//Load messages
const LOAD_ALL_MESSAGES = 'LOAD_ALL_MESSAGES';
const LOAD_ALL_MESSAGES_REQUEST = 'LOAD_ALL_MESSAGES_REQUEST';
const LOAD_ALL_MESSAGES_SUCCESS = 'LOAD_ALL_MESSAGES_SUCCESS';
const LOAD_ALL_MESSAGES_FAILURE = 'LOAD_ALL_MESSAGES_FAILURE';

const LOAD_ALL_MESSAGES_ON_ISSUES = 'LOAD_ALL_MESSAGES_ON_ISSUES';
const LOAD_ALL_MESSAGES_ON_ISSUES_REQUEST = 'LOAD_ALL_MESSAGES_ON_ISSUES_REQUEST';
const LOAD_ALL_MESSAGES_ON_ISSUES_SUCCESS = 'LOAD_ALL_MESSAGES_ON_ISSUES_SUCCESS';
const LOAD_ALL_MESSAGES_ON_ISSUES_FAILURE = 'LOAD_ALL_MESSAGES_ON_ISSUES_FAILURE';

//Edit message
const EDIT_MESSAGE = 'EDIT_MESSAGE';
const EDIT_MESSAGE_REQUEST = 'EDIT_MESSAGE_REQUEST';
const EDIT_MESSAGE_SUCCESS = 'EDIT_MESSAGE_SUCCESS';
const EDIT_MESSAGE_FAILURE = 'EDIT_MESSAGE_FAILURE';

//Reset message
const RESET_MESSAGE = 'RESET_MESSAGE';

export {
  CREATE_MESSAGE,
  CREATE_MESSAGE_REQUEST,
  CREATE_MESSAGE_SUCCESS,
  CREATE_MESSAGE_FAILURE,
  LOAD_ALL_MESSAGES,
  LOAD_ALL_MESSAGES_REQUEST,
  LOAD_ALL_MESSAGES_SUCCESS,
  LOAD_ALL_MESSAGES_FAILURE,
  LOAD_ALL_MESSAGES_ON_ISSUES,
  LOAD_ALL_MESSAGES_ON_ISSUES_REQUEST,
  LOAD_ALL_MESSAGES_ON_ISSUES_SUCCESS,
  LOAD_ALL_MESSAGES_ON_ISSUES_FAILURE,
  EDIT_MESSAGE,
  EDIT_MESSAGE_REQUEST,
  EDIT_MESSAGE_SUCCESS,
  EDIT_MESSAGE_FAILURE,
  RESET_MESSAGE
}
