// Login
const LOGIN_USER = 'account/LOGIN_USER';
const LOGIN_REQUEST = 'account/LOGIN_REQUEST';
const LOGIN_SUCCESS = 'account/LOGIN_SUCCESS';
const LOGIN_FAILURE = 'account/LOGIN_FAILURE';
//Sign Up
const SIGN_UP_USER = 'account/SIGN_UP_USER';
const SIGN_UP_REQUEST = 'account/SIGN_UP_REQUEST';
const SIGN_UP_SUCCESS = 'account/SIGN_UP_SUCCESS';
const SIGN_UP_FAILURE = 'account/SIGN_UP_FAILURE';
//Log Out
const LOG_OUT = 'account/LOG_OUT';
const REQUEST_LOG_OUT = 'account/REQUEST_LOG_OUT';
const LOG_OUT_SUCCESS = 'account/LOG_OUT_SUCCESS';
const LOG_OUT_FAILURE = 'account/LOG_OUT_FAILURE';
//Accounts
const LOAD_ALL_USERS = 'account/LOAD_ALL_USERS';
const LOAD_ALL_USERS_SUCCESS = 'account/LOAD_ALL_USERS_SUCCESS';
const LOAD_ALL_USERS_FAILURE = 'account/LOAD_ALL_USERS_FAILURE';
//Update
const UPDATE_PROFILE = 'account/UPDATE_PROFILE';
const UPDATE_PROFILE_REQUEST = 'account/UPDATE_PROFILE_REQUEST';
const UPDATE_PROFILE_SUCCESS = 'account/UPDATE_PROFILE_SUCCESS';
const UPDATE_PROFILE_FAILURE = 'account/UPDATE_PROFILE_FAILURE';
//Remove
const REMOVE_USER ='account/REMOVE_USER';
const REMOVE_USER_REQUEST ='account/REMOVE_USER_REQUEST';
const REMOVE_USER_SUCCESS ='account/REMOVE_USER_SUCCESS';
const REMOVE_USER_FAILURE ='account/REMOVE_USER_FAILURE';

export {
  LOGIN_USER,
  LOGIN_SUCCESS,
  LOGIN_REQUEST,
  LOGIN_FAILURE,
  SIGN_UP_USER,
  SIGN_UP_REQUEST,
  SIGN_UP_SUCCESS,
  SIGN_UP_FAILURE,
  LOG_OUT,
  REQUEST_LOG_OUT,
  LOG_OUT_SUCCESS,
  LOG_OUT_FAILURE,
  LOAD_ALL_USERS,
  LOAD_ALL_USERS_SUCCESS,
  LOAD_ALL_USERS_FAILURE,
  UPDATE_PROFILE,
  UPDATE_PROFILE_REQUEST,
  UPDATE_PROFILE_SUCCESS,
  UPDATE_PROFILE_FAILURE,
  REMOVE_USER,
  REMOVE_USER_REQUEST,
  REMOVE_USER_SUCCESS,
  REMOVE_USER_FAILURE

}
