const GET_ISSUE_SUMMARY = 'GET_ISSUE_SUMMARY';
const GET_ISSUE_SUMMARY_REQUEST = 'GET_ISSUE_SUMMARY_REQUEST';
const GET_ISSUE_SUMMARY_SUCCESS = 'GET_ISSUE_SUMMARY_SUCCESS';
const GET_ISSUE_SUMMARY_FAILURE = 'GET_ISSUE_SUMMARY_FAILURE';

const RESET_SUMMARY = 'RESET_SUMMARY';

export {
  GET_ISSUE_SUMMARY,
  GET_ISSUE_SUMMARY_REQUEST,
  GET_ISSUE_SUMMARY_SUCCESS,
  GET_ISSUE_SUMMARY_FAILURE,
  RESET_SUMMARY
}
