const GET_ISSUE_SUMMARY = 'GET_ISSUE_SUMMARY';
const GET_ISSUE_SUMMARY_REQUEST = 'GET_ISSUE_SUMMARY_REQUEST';
const GET_ISSUE_SUMMARY_SUCCESS = 'GET_ISSUE_SUMMARY_SUCCESS';
const GET_ISSUE_SUMMARY_FAILURE = 'GET_ISSUE_SUMMARY_FAILURE';

const GET_ISSUE_SUMMARY_DETAILS = 'GET_ISSUE_SUMMARY_DETAILS';
const GET_ISSUE_SUMMARY_DETAILS_REQUEST = 'GET_ISSUE_SUMMARY_DETAILS_REQUEST';
const GET_ISSUE_SUMMARY_DETAILS_SUCCESS = 'GET_ISSUE_SUMMARY_DETAILS_SUCCESS';
const GET_ISSUE_SUMMARY_DETAILS_FAILURE = 'GET_ISSUE_SUMMARY_DETAILS_FAILURE';

const RESET_SUMMARY = 'RESET_SUMMARY';
const RESET_SUMMARY_DETAILS = 'RESET_SUMMARY_DETAILS';

export {
  GET_ISSUE_SUMMARY,
  GET_ISSUE_SUMMARY_REQUEST,
  GET_ISSUE_SUMMARY_SUCCESS,
  GET_ISSUE_SUMMARY_FAILURE,
  GET_ISSUE_SUMMARY_DETAILS,
  GET_ISSUE_SUMMARY_DETAILS_REQUEST,
  GET_ISSUE_SUMMARY_DETAILS_SUCCESS,
  GET_ISSUE_SUMMARY_DETAILS_FAILURE,
  RESET_SUMMARY,
  RESET_SUMMARY_DETAILS
}
