const CREATE_PROJECT = 'CREATE_PROJECT';
const REQUEST_CREATE_PROJECT = 'REQUEST_CREATE_PROJECT';
const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE';

const LOAD_ALL_PROJECTS = 'LOAD_ALL_PROJECTS';
const LOAD_ALL_PROJECTS_SUCCESS = 'LOAD_ALL_PROJECTS_SUCCESS';
const LOAD_ALL_PROJECTS_FAILURE = 'LOAD_ALL_PROJECTS_FAILURE';

export {
  CREATE_PROJECT,
  REQUEST_CREATE_PROJECT,
  CREATE_PROJECT_SUCCESS,
  CREATE_PROJECT_FAILURE,
  LOAD_ALL_PROJECTS,
  LOAD_ALL_PROJECTS_SUCCESS,
  LOAD_ALL_PROJECTS_FAILURE
}
