//Create Project
const CREATE_PROJECT = 'CREATE_PROJECT';
const REQUEST_CREATE_PROJECT = 'REQUEST_CREATE_PROJECT';
const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE';
//Load Project
const LOAD_ALL_PROJECTS = 'LOAD_ALL_PROJECTS';
const LOAD_ALL_PROJECTS_SUCCESS = 'LOAD_ALL_PROJECTS_SUCCESS';
const LOAD_ALL_PROJECTS_FAILURE = 'LOAD_ALL_PROJECTS_FAILURE';
//Add user to Project
const ADD_USER_TO_PROJECT = 'ADD_USER_TO_PROJECT';
const ADD_USER_TO_PROJECT_REQUEST = 'ADD_USER_TO_PROJECT_REQUEST';
const ADD_USER_TO_PROJECT_SUCCESS = 'ADD_USER_TO_PROJECT_SUCCESS';
const ADD_USER_TO_PROJECT_FAILURE = 'ADD_USER_TO_PROJECT_FAILURE';

export {
  CREATE_PROJECT,
  REQUEST_CREATE_PROJECT,
  CREATE_PROJECT_SUCCESS,
  CREATE_PROJECT_FAILURE,
  LOAD_ALL_PROJECTS,
  LOAD_ALL_PROJECTS_SUCCESS,
  LOAD_ALL_PROJECTS_FAILURE,
  ADD_USER_TO_PROJECT,
  ADD_USER_TO_PROJECT_REQUEST,
  ADD_USER_TO_PROJECT_SUCCESS,
  ADD_USER_TO_PROJECT_FAILURE
}
