//Create Project
const CREATE_PROJECT = 'CREATE_PROJECT';
const REQUEST_CREATE_PROJECT = 'REQUEST_CREATE_PROJECT';
const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE';
<<<<<<< HEAD

=======
//Load Project
>>>>>>> b10d732a9ec0638f8289d4a2111044605efa68c9
const LOAD_ALL_PROJECTS = 'LOAD_ALL_PROJECTS';
const LOAD_ALL_PROJECTS_SUCCESS = 'LOAD_ALL_PROJECTS_SUCCESS';
const LOAD_ALL_PROJECTS_FAILURE = 'LOAD_ALL_PROJECTS_FAILURE';
//Add user to Project
const ADD_USER_TO_PROJECT = 'ADD_USER_TO_PROJECT';
const ADD_USER_TO_PROJECT_REQUEST = 'ADD_USER_TO_PROJECT_REQUEST';
const ADD_USER_TO_PROJECT_SUCCESS = 'ADD_USER_TO_PROJECT_SUCCESS';
const ADD_USER_TO_PROJECT_FAILURE = 'ADD_USER_TO_PROJECT_FAILURE';
//Load users in Project
const LOAD_ALL_USERS_IN_PROJECT = 'LOAD_ALL_USERS_IN_PROJECT';
const LOAD_ALL_USERS_IN_PROJECT_REQUEST = 'LOAD_ALL_USERS_IN_PROJECT_REQUEST';
const LOAD_ALL_USERS_IN_PROJECT_SUCCESS = 'LOAD_ALL_USERS_IN_PROJECT_SUCCESS';
const LOAD_ALL_USERS_IN_PROJECT_FAILURE = 'LOAD_ALL_USERS_IN_PROJECT_FAILURE';
//Load project by id
const LOAD_PROJECT_BY_ID = 'LOAD_PROJECT_BY_ID';
const LOAD_PROJECT_BY_ID_REQUEST = 'LOAD_PROJECT_BY_ID_REQUEST';
const LOAD_PROJECT_BY_ID_SUCCESS = 'LOAD_PROJECT_BY_ID_SUCCESS';
const LOAD_PROJECT_BY_ID_FAILURE = 'LOAD_PROJECT_BY_ID_FAILURE';

export {
  CREATE_PROJECT,
  REQUEST_CREATE_PROJECT,
  CREATE_PROJECT_SUCCESS,
  CREATE_PROJECT_FAILURE,
  LOAD_ALL_PROJECTS,
  LOAD_ALL_PROJECTS_SUCCESS,
  LOAD_ALL_PROJECTS_FAILURE,
  ADD_USER_TO_PROJECT,
  ADD_USER_TO_PROJECT_REQUEST,
  ADD_USER_TO_PROJECT_SUCCESS,
  ADD_USER_TO_PROJECT_FAILURE,
  LOAD_ALL_USERS_IN_PROJECT,
  LOAD_ALL_USERS_IN_PROJECT_REQUEST,
  LOAD_ALL_USERS_IN_PROJECT_SUCCESS,
  LOAD_ALL_USERS_IN_PROJECT_FAILURE,
  LOAD_PROJECT_BY_ID,
  LOAD_PROJECT_BY_ID_REQUEST,
  LOAD_PROJECT_BY_ID_SUCCESS,
  LOAD_PROJECT_BY_ID_FAILURE
}
