const LOAD_NOTIFICATION = 'LOAD_NOTIFICATION';
const LOAD_NOTIFICATION_REQUEST = 'LOAD_NOTIFICATION_REQUEST';
const LOAD_NOTIFICATION_SUCCESS = 'LOAD_NOTIFICATION_SUCCESS';
const LOAD_NOTIFICATION_FAILURE = 'LOAD_NOTIFICATION_FAILURE';

const LOAD_NOTIFICATIONS = 'LOAD_NOTIFICATIONS';
const LOAD_NOTIFICATIONS_REQUEST = 'LOAD_NOTIFICATIONS_REQUEST';
const LOAD_NOTIFICATIONS_SUCCESS = 'LOAD_NOTIFICATIONS_SUCCESS';
const LOAD_NOTIFICATIONS_FAILURE = 'LOAD_NOTIFICATIONS_FAILURE';

const SET_NOTIFICATION_TO_SEEN = 'SET_NOTIFICATION_TO_SEEN';
const SET_NOTIFICATION_TO_SEEN_REQUEST = 'SET_NOTIFICATION_TO_REQUEST';
const SET_NOTIFICATION_TO_SEEN_SUCCESS = 'SET_NOTIFICATION_TO_SEEN_SUCCESS';
const SET_NOTIFICATION_TO_SEEN_FAILURE = 'SET_NOTIFICATION_TO_SEEN_FAILURE';

const SET_NOTIFICATION_TO_READ = 'SET_NOTIFICATION_TO_READ';
const SET_NOTIFICATION_TO_READ_REQUEST = 'SET_NOTIFICATION_TO_READ_REQUEST';
const SET_NOTIFICATION_TO_READ_SUCCESS = 'SET_NOTIFICATION_TO_READ_SUCCESS';
const SET_NOTIFICATION_TO_READ_FAILURE = 'SET_NOTIFICATION_TO_SEEN_FAILURE';

const SET_ALL_NOTIFICATIONS_TO_SEEN = 'SET_ALL_NOTIFICATIONS_TO_SEEN';
const SET_ALL_NOTIFICATIONS_TO_SEEN_REQUEST = 'SET_ALL_NOTIFICATIONS_TO_SEEN_REQUEST';
const SET_ALL_NOTIFICATIONS_TO_SEEN_SUCCESS = 'SET_ALL_NOTIFICATIONS_TO_SEEN_SUCCESS';
const SET_ALL_NOTIFICATIONS_TO_SEEN_FAILURE = 'SET_ALL_NOTIFICATIONS_TO_SEEN_FAILURE';

const SET_ALL_NOTIFICATIONS_TO_READ = 'SET_ALL_NOTIFICATIONS_TO_READ';
const SET_ALL_NOTIFICATIONS_TO_READ_REQUEST = 'SET_ALL_NOTIFICATIONS_TO_READ_REQUEST';
const SET_ALL_NOTIFICATIONS_TO_READ_SUCCESS = 'SET_ALL_NOTIFICATIONS_TO_READ_SUCCESS';
const SET_ALL_NOTIFICATIONS_TO_READ_FAILURE = 'SET_ALL_NOTIFICATIONS_TO_SEEN_FAILURE';

const SET_ALL_NOTIFICATIONS_TO_DELETE = 'SET_ALL_NOTIFICATIONS_TO_DELETE';
const SET_ALL_NOTIFICATIONS_TO_DELETE_REQUEST = 'SET_ALL_NOTIFICATIONS_TO_DELETE_REQUEST';
const SET_ALL_NOTIFICATIONS_TO_DELETE_SUCCESS = 'SET_ALL_NOTIFICATIONS_TO_DELETE_SUCCESS';
const SET_ALL_NOTIFICATIONS_TO_DELETE_FAILURE = 'SET_ALL_NOTIFICATIONS_TO_SEEN_FAILURE';

export {
  LOAD_NOTIFICATION,
  LOAD_NOTIFICATION_REQUEST,
  LOAD_NOTIFICATION_SUCCESS,
  LOAD_NOTIFICATION_FAILURE,
  LOAD_NOTIFICATIONS,
  LOAD_NOTIFICATIONS_REQUEST,
  LOAD_NOTIFICATIONS_SUCCESS,
  LOAD_NOTIFICATIONS_FAILURE,
  SET_NOTIFICATION_TO_SEEN,
  SET_NOTIFICATION_TO_SEEN_REQUEST,
  SET_NOTIFICATION_TO_SEEN_SUCCESS,
  SET_NOTIFICATION_TO_SEEN_FAILURE,
  SET_NOTIFICATION_TO_READ,
  SET_NOTIFICATION_TO_READ_REQUEST,
  SET_NOTIFICATION_TO_READ_SUCCESS,
  SET_NOTIFICATION_TO_READ_FAILURE,
  SET_ALL_NOTIFICATIONS_TO_SEEN,
  SET_ALL_NOTIFICATIONS_TO_SEEN_REQUEST,
  SET_ALL_NOTIFICATIONS_TO_SEEN_SUCCESS,
  SET_ALL_NOTIFICATIONS_TO_SEEN_FAILURE,
  SET_ALL_NOTIFICATIONS_TO_READ,
  SET_ALL_NOTIFICATIONS_TO_READ_REQUEST,
  SET_ALL_NOTIFICATIONS_TO_READ_SUCCESS,
  SET_ALL_NOTIFICATIONS_TO_READ_FAILURE,
  SET_ALL_NOTIFICATIONS_TO_DELETE,
  SET_ALL_NOTIFICATIONS_TO_DELETE_REQUEST,
  SET_ALL_NOTIFICATIONS_TO_DELETE_SUCCESS,
  SET_ALL_NOTIFICATIONS_TO_DELETE_FAILURE
}
