// Create
const CREATE_ISSUE = 'CREATE_ISSUE';
const CREATE_ISSUE_REQUEST = 'CREATE_ISSUE_REQUEST';
const CREATE_ISSUE_SUCCESS = 'CREATE_ISSUE_SUCCESS';
const CREATE_ISSUE_FAILURE = 'CREATE_ISSUE_FAILURE';
// Load
const LOAD_ALL_ISSUES = 'LOAD_ALL_ISSUES';
const LOAD_ALL_ISSUES_SUCCESS = 'LOAD_ALL_ISSUES_SUCCESS';
const LOAD_ALL_ISSUES_FAILURE = 'LOAD_ALL_ISSUES_FAILURE';

const LOAD_ALL_ISSUES_SHORTCUT = 'LOAD_ALL_ISSUES_SHORTCUT';
const LOAD_ALL_ISSUES_SHORTCUT_REQUEST = 'LOAD_ALL_ISSUES_SHORTCUT_REQUEST';
const LOAD_ALL_ISSUES_SHORTCUT_SUCCESS = 'LOAD_ALL_ISSUES_SHORTCUT_SUCCESS';
const LOAD_ALL_ISSUES_SHORTCUT_FAILURE = 'LOAD_ALL_ISSUES_SHORTCUT_FAILURE';

const LOAD_ISSUE_DETAILS = 'LOAD_ISSUE_DETAILS';
const LOAD_ISSUE_DETAILS_REQUEST = 'LOAD_ISSUE_DETAILS_REQUEST';
const LOAD_ISSUE_DETAILS_SUCCESS = 'LOAD_ISSUE_DETAILS_SUCCESS';
const LOAD_ISSUE_DETAILS_FAILURE = 'LOAD_ISSUE_DETAILS_FAILURE';
//Update
const UPDATE_ISSUE = 'UPDATE_ISSUE';
const UPDATE_ISSUE_REQUEST = 'UPDATE_ISSUE_REQUEST';
const UPDATE_ISSUE_SUCCESS = 'UPDATE_ISSUE_SUCCESS';
const UPDATE_ISSUE_FAILURE = 'UPDATE_ISSUE_FAILURE';
//Reset
const RESET_ISSUE_DETAILS = 'RESET_ISSUE_DETAILS';

export {
  CREATE_ISSUE,
  CREATE_ISSUE_REQUEST,
  CREATE_ISSUE_SUCCESS,
  CREATE_ISSUE_FAILURE,
  LOAD_ALL_ISSUES,
  LOAD_ALL_ISSUES_SUCCESS,
  LOAD_ALL_ISSUES_FAILURE,
  LOAD_ALL_ISSUES_SHORTCUT,
  LOAD_ALL_ISSUES_SHORTCUT_REQUEST,
  LOAD_ALL_ISSUES_SHORTCUT_SUCCESS,
  LOAD_ALL_ISSUES_SHORTCUT_FAILURE,
  LOAD_ISSUE_DETAILS,
  LOAD_ISSUE_DETAILS_REQUEST,
  LOAD_ISSUE_DETAILS_SUCCESS,
  LOAD_ISSUE_DETAILS_FAILURE,
  UPDATE_ISSUE,
  UPDATE_ISSUE_REQUEST,
  UPDATE_ISSUE_SUCCESS,
  UPDATE_ISSUE_FAILURE,
  RESET_ISSUE_DETAILS
}
