const CREATE_ISSUE = 'CREATE_ISSUE';
const CREATE_ISSUE_REQUEST = 'CREATE_ISSUE_REQUEST';
const CREATE_ISSUE_SUCCESS = 'CREATE_ISSUE_SUCCESS';
const CREATE_ISSUE_FAILURE = 'CREATE_ISSUE_FAILURE';
const LOAD_ALL_ISSUES = 'LOAD_ALL_ISSUES';
const LOAD_ALL_ISSUES_SUCCESS = 'LOAD_ALL_ISSUES_SUCCESS';
const LOAD_ALL_ISSUES_FAILURE = 'LOAD_ALL_ISSUES_FAILURE';

export {
  CREATE_ISSUE,
  CREATE_ISSUE_REQUEST,
  CREATE_ISSUE_SUCCESS,
  CREATE_ISSUE_FAILURE,
  LOAD_ALL_ISSUES,
  LOAD_ALL_ISSUES_SUCCESS,
  LOAD_ALL_ISSUES_FAILURE
}
