//Category
const CREATE_CATEGORY = 'CREATE_CATEGORY';
const REQUEST_CREATE_CATEGORY = 'REQUEST_CREATE_CATEGORY';
const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
const CREATE_CATEGORY_FAILURE = 'CREATE_CATEGORY_FAILURE';

const LOAD_ALL_CATEGORIES = 'LOAD_ALL_CATEGORIES';
const LOAD_ALL_CATEGORIES_REQUEST = 'LOAD_ALL_CATEGORIES_REQUEST';
const LOAD_ALL_CATEGORIES_SUCCESS = 'LOAD_ALL_CATEGORIES_SUCCESS';
const LOAD_ALL_CATEGORIES_FAILURE = 'LOAD_ALL_CATEGORIES_FAILURE';

export {
  CREATE_CATEGORY,
  REQUEST_CREATE_CATEGORY,
  CREATE_CATEGORY_SUCCESS,
  CREATE_CATEGORY_FAILURE,
  LOAD_ALL_CATEGORIES,
  LOAD_ALL_CATEGORIES_REQUEST,
  LOAD_ALL_CATEGORIES_SUCCESS,
  LOAD_ALL_CATEGORIES_FAILURE
}
