<<<<<<< HEAD
const BAN_USER = 'BAN_USER';
const REQUEST_BAN_USER = 'REQUEST_BAN_USER';
const BAN_USER_SUCCESS = 'BAN_USER_SUCCESS';
const BAN_USER_FAILURE = 'BAN_USER_FAILURE';

export {
    BAN_USER,
    REQUEST_BAN_USER,
    BAN_USER_SUCCESS,
    BAN_USER_FAILURE
    
  }
  
=======
//Category
const CREATE_CATEGORY = 'CREATE_CATEGORY';
const REQUEST_CREATE_CATEGORY = 'REQUEST_CREATE_CATEGORY';
const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
const CREATE_CATEGORY_FAILURE = 'CREATE_CATEGORY_FAILURE';

const LOAD_ALL_CATEGORIES = 'LOAD_ALL_CATEGORIES';
const LOAD_ALL_CATEGORIES_REQUEST = 'LOAD_ALL_CATEGORIES_REQUEST';
const LOAD_ALL_CATEGORIES_SUCCESS = 'LOAD_ALL_CATEGORIES_SUCCESS';
const LOAD_ALL_CATEGORIES_FAILURE = 'LOAD_ALL_CATEGORIES_FAILURE';

export {
  CREATE_CATEGORY,
  REQUEST_CREATE_CATEGORY,
  CREATE_CATEGORY_SUCCESS,
  CREATE_CATEGORY_FAILURE,
  LOAD_ALL_CATEGORIES,
  LOAD_ALL_CATEGORIES_REQUEST,
  LOAD_ALL_CATEGORIES_SUCCESS,
  LOAD_ALL_CATEGORIES_FAILURE
}
>>>>>>> b10d732a9ec0638f8289d4a2111044605efa68c9
