//Category
const CREATE_CATEGORY = 'CREATE_CATEGORY';
const REQUEST_CREATE_CATEGORY = 'REQUEST_CREATE_CATEGORY';
const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
const CREATE_CATEGORY_FAILURE = 'CREATE_CATEGORY_FAILURE';

const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST';
const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
const UPDATE_CATEGORY_FAILURE = 'UPDATE_CATEGORY_FAILURE';

const LOAD_ALL_CATEGORIES = 'LOAD_ALL_CATEGORIES';
const LOAD_ALL_CATEGORIES_REQUEST = 'LOAD_ALL_CATEGORIES_REQUEST';
const LOAD_ALL_CATEGORIES_SUCCESS = 'LOAD_ALL_CATEGORIES_SUCCESS';
const LOAD_ALL_CATEGORIES_FAILURE = 'LOAD_ALL_CATEGORIES_FAILURE';

const LOAD_CATEGORY_DETAILS = 'LOAD_CATEGORY_DETAILS';
const LOAD_CATEGORY_DETAILS_REQUEST = 'LOAD_CATEGORY_DETAILS_REQUEST';
const LOAD_CATEGORY_DETAILS_SUCCESS = 'LOAD_CATEGORY_DETAILS_SUCCESS';
const LOAD_CATEGORY_DETAILS_FAILURE = 'LOAD_CATEGORY_DETAILS_FAILURE';

const DELETE_CATEGORY = 'DELETE_CATEGORY';
const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE';

const BAN_USER = 'BAN_USER';
const REQUEST_BAN_USER = 'REQUEST_BAN_USER';
const BAN_USER_SUCCESS = 'BAN_USER_SUCCESS';
const BAN_USER_FAILURE = 'BAN_USER_FAILURE';

const CREATE_STATUS = 'CREATE_STATUS';
const REQUEST_CREATE_STATUS = 'REQUEST_CREATE_STATUS';
const CREATE_STATUS_FAILURE = 'CREATE_STATUS_FAILURE';
const CREATE_STATUS_SUCCESS = 'CREATE_STATUS_SUCCESS';

const LOAD_ALL_STATUS = 'LOAD_ALL_STATUS';
const LOAD_ALL_STATUS_REQUEST = 'LOAD_ALL_STATUS_REQUEST';
const LOAD_ALL_STATUS_SUCCESS = 'LOAD_ALL_STATUS_SUCCESS';
const LOAD_ALL_STATUS_FAILURE = 'LOAD_ALL_STATUS_FAILURE';

const LOAD_STATUS_DETAILS = 'LOAD_STATUS_DETAILS';
const LOAD_STATUS_DETAILS_REQUEST = 'LOAD_STATUS_DETAILS_REQUEST';
const LOAD_STATUS_DETAILS_SUCCESS = 'LOAD_STATUS_DETAILS_SUCCESS';
const LOAD_STATUS_DETAILS_FAILURE = 'LOAD_STATUS_DETAILS_FAILURE';

const REMOVE_STATUS = 'REMOVE_STATUS';
const REQUEST_REMOVE_STATUS ='REQUEST_REMOVE_STATUS';
const REMOVE_STATUS_FAILURE = 'REMOVE_STATUS_FAILURE';
const REMOVE_STATUS_SUCCESS = 'REMOVE_STATUS_SUCCESS';

const UPDATE_STATUS = 'UPDATE_STATUS';
const REQUEST_UPDATE_STATUS = 'REQUEST_UPDATE_STATUS';
const UPDATE_STATUS_FAILURE = 'UPDATE_STATUS_FAILURE';
const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS';

const UPDATE_STATUS_DEFAULT = 'UPDATE_STATUS_DEFAULT';
const REQUEST_UPDATE_STATUS_DEFAULT = 'REQUEST_UPDATE_STATUS_DEFAULT';
const UPDATE_STATUS_DEFAULT_FAILURE = 'UPDATE_STATUS_DEFAULT_FAILURE';
const UPDATE_STATUS_DEFAULT_SUCCESS = 'UPDATE_STATUS_DEFAULT_SUCCESS';

const LOAD_ALL_PROJECTS_FOR_MANAGEMENT = 'LOAD_ALL_PROJECTS_FOR_MANAGEMENT';
const LOAD_ALL_PROJECTS_FOR_MANAGEMENT_REQUEST = 'LOAD_ALL_PROJECTS_FOR_MANAGEMENT_REQUEST';
const LOAD_ALL_PROJECTS_FOR_MANAGEMENT_SUCCESS = 'LOAD_ALL_PROJECTS_FOR_MANAGEMENT_SUCCESS';
const LOAD_ALL_PROJECTS_FOR_MANAGEMENT_FAILURE = 'LOAD_ALL_PROJECTS_FOR_MANAGEMENT_FAILURE';

const LOAD_ALL_KPI = 'LOAD_ALL_KPI';
const LOAD_ALL_KPI_REQUEST = 'LOAD_ALL_KPI_REQUEST';
const LOAD_ALL_KPI_SUCCESS = 'LOAD_ALL_KPI_SUCCESS';
const LOAD_ALL_KPI_FAILURE = 'LOAD_ALL_KPI_FAILURE';

const UPDATE_KPI = 'UPDATE_KPI';
const UPDATE_KPI_REQUEST = 'UPDATE_KPI_REQUEST';
const UPDATE_KPI_SUCCESS = 'UPDATE_KPI_SUCCESS';
const UPDATE_KPI_FAILURE = 'UPDATE_KPI_FAILURE';

const LOAD_USERS_KPI = 'LOAD_USERS_KPI';
const LOAD_USERS_KPI_REQUEST = 'LOAD_USERS_KPI_REQUEST';
const LOAD_USERS_KPI_SUCCESS = 'LOAD_USERS_KPI_SUCCESS';
const LOAD_USERS_KPI_FAILURE = 'LOAD_USERS_KPI_FAILURE';

const RESET_STATUS = 'RESET_STATUS';
const RESET_CATEGORY = 'RESET_CATEGORY';

export {
  UPDATE_STATUS_DEFAULT,
  REQUEST_UPDATE_STATUS_DEFAULT,
  UPDATE_STATUS_DEFAULT_FAILURE,
  UPDATE_STATUS_DEFAULT_SUCCESS,
  CREATE_STATUS,
  REQUEST_CREATE_STATUS,
  CREATE_STATUS_FAILURE,
  CREATE_STATUS_SUCCESS,
  LOAD_ALL_STATUS,
  LOAD_ALL_STATUS_REQUEST,
  LOAD_ALL_STATUS_SUCCESS,
  LOAD_ALL_STATUS_FAILURE,
  LOAD_STATUS_DETAILS,
  LOAD_STATUS_DETAILS_REQUEST,
  LOAD_STATUS_DETAILS_SUCCESS,
  LOAD_STATUS_DETAILS_FAILURE,
  REMOVE_STATUS,
  REQUEST_REMOVE_STATUS,
  REMOVE_STATUS_FAILURE,
  REMOVE_STATUS_SUCCESS,
  UPDATE_STATUS,
  REQUEST_UPDATE_STATUS,
  UPDATE_STATUS_FAILURE,
  UPDATE_STATUS_SUCCESS,
  CREATE_CATEGORY,
  REQUEST_CREATE_CATEGORY,
  CREATE_CATEGORY_SUCCESS,
  CREATE_CATEGORY_FAILURE,
  UPDATE_CATEGORY,
  UPDATE_CATEGORY_REQUEST,
  UPDATE_CATEGORY_SUCCESS,
  UPDATE_CATEGORY_FAILURE,
  LOAD_ALL_CATEGORIES,
  LOAD_ALL_CATEGORIES_REQUEST,
  LOAD_ALL_CATEGORIES_SUCCESS,
  LOAD_ALL_CATEGORIES_FAILURE,
  LOAD_CATEGORY_DETAILS,
  LOAD_CATEGORY_DETAILS_REQUEST,
  LOAD_CATEGORY_DETAILS_SUCCESS,
  LOAD_CATEGORY_DETAILS_FAILURE,
  DELETE_CATEGORY,
  DELETE_CATEGORY_REQUEST,
  DELETE_CATEGORY_SUCCESS,
  DELETE_CATEGORY_FAILURE,
  BAN_USER,
  REQUEST_BAN_USER,
  BAN_USER_SUCCESS,
  BAN_USER_FAILURE,
  LOAD_ALL_PROJECTS_FOR_MANAGEMENT,
  LOAD_ALL_PROJECTS_FOR_MANAGEMENT_REQUEST,
  LOAD_ALL_PROJECTS_FOR_MANAGEMENT_SUCCESS,
  LOAD_ALL_PROJECTS_FOR_MANAGEMENT_FAILURE,
  LOAD_ALL_KPI,
  LOAD_ALL_KPI_REQUEST,
  LOAD_ALL_KPI_SUCCESS,
  LOAD_ALL_KPI_FAILURE,
  UPDATE_KPI,
  UPDATE_KPI_REQUEST,
  UPDATE_KPI_SUCCESS,
  UPDATE_KPI_FAILURE,
  LOAD_USERS_KPI,
  LOAD_USERS_KPI_REQUEST,
  LOAD_USERS_KPI_SUCCESS,
  LOAD_USERS_KPI_FAILURE,
  RESET_STATUS,
  RESET_CATEGORY
}
