//Create Phase
const CREATE_PHASE = 'CREATE_PHASE';
const REQUEST_CREATE_PHASE = 'REQUEST_CREATE_PHASE';
const CREATE_PHASE_SUCCESS = 'CREATE_PHASE_SUCCESS';
const CREATE_PHASE_FAILURE = 'CREATE_PHASE_FAILURE';
//Load Phase
const LOAD_ALL_PHASES = 'LOAD_ALL_PHASES';
const LOAD_ALL_PHASES_REQUEST = 'LOAD_ALL_PHASES_REQUEST';
const LOAD_ALL_PHASES_SUCCESS = 'LOAD_ALL_PHASES_SUCCESS';
const LOAD_ALL_PHASES_FAILURE = 'LOAD_ALL_PHASES_FAILURE';
//Update Phase
const UPDATE_PHASE_ISSUES_LIST = 'UPDATE_PHASE_ISSUES_LIST';
const UPDATE_PHASE_ISSUES_LIST_REQUEST = 'UPDATE_PHASE_ISSUES_LIST_REQUEST';
const UPDATE_PHASE_ISSUES_LIST_SUCCESS = 'UPDATE_PHASE_ISSUES_LIST_SUCCESS';
const UPDATE_PHASE_ISSUES_LIST_FAILURE = 'UPDATE_PHASE_ISSUES_LIST_FAILURE';
//Reset Phase
const RESET_PHASE = 'RESET_PHASE';

export {
  CREATE_PHASE,
  REQUEST_CREATE_PHASE,
  CREATE_PHASE_SUCCESS,
  CREATE_PHASE_FAILURE,
  LOAD_ALL_PHASES,
  LOAD_ALL_PHASES_REQUEST,
  LOAD_ALL_PHASES_SUCCESS,
  LOAD_ALL_PHASES_FAILURE,
  UPDATE_PHASE_ISSUES_LIST,
  UPDATE_PHASE_ISSUES_LIST_REQUEST,
  UPDATE_PHASE_ISSUES_LIST_SUCCESS,
  UPDATE_PHASE_ISSUES_LIST_FAILURE,
  RESET_PHASE
}
