//Create Project
const CREATE_PHASE = 'CREATE_PHASE';
const REQUEST_CREATE_PHASE = 'REQUEST_CREATE_PHASE';
const CREATE_PHASE_SUCCESS = 'CREATE_PHASE_SUCCESS';
const CREATE_PHASE_FAILURE = 'CREATE_PHASE_FAILURE';
//Load Project
const LOAD_ALL_PHASES = 'LOAD_ALL_PHASES';
const LOAD_ALL_PHASES_REQUEST = 'LOAD_ALL_PHASES_REQUEST';
const LOAD_ALL_PHASES_SUCCESS = 'LOAD_ALL_PHASES_SUCCESS';
const LOAD_ALL_PHASES_FAILURE = 'LOAD_ALL_PHASES_FAILURE';

export {
  CREATE_PHASE,
  REQUEST_CREATE_PHASE,
  CREATE_PHASE_SUCCESS,
  CREATE_PHASE_FAILURE,
  LOAD_ALL_PHASES,
  LOAD_ALL_PHASES_REQUEST,
  LOAD_ALL_PHASES_SUCCESS,
  LOAD_ALL_PHASES_FAILURE
}
