//Load User
const LOAD_CURRENT_USER = 'account/LOAD_CURRENT_USER';
const REQUEST_LOAD_CURRENT_USER = 'account/REQUEST_LOAD_CURRENT_USER';
const LOAD_CURRENT_USER_SUCCESS = 'account/LOAD_CURRENT_USER_SUCCESS';
const LOAD_CURRENT_USER_FAILURE = 'account/LOAD_CURRENT_USER_FAILURE';
//Update User Role
const UPDATE_CURRENT_USER_ROLE = 'UPDATE_CURRENT_USER_ROLE';
//Reset User
const RESET_USER = 'RESET_USER';
//Modal
const OPEN_MODAL = 'OPEN_MODAL';
const CLOSE_MODAL = 'CLOSE_MODAL';
//Load Project Details
const LOAD_PROJECT_DETAILS = 'LOAD_PROJECT_DETAILS';
const LOAD_PROJECT_DETAILS_REQUEST = 'LOAD_PROJECT_DETAILS_REQUEST';
const LOAD_PROJECT_DETAILS_SUCCESS = 'LOAD_PROJECT_DETAILS_SUCCESS';
const LOAD_PROJECT_DETAILS_FAILURE = 'LOAD_PROJECT_DETAILS_FAILURE';
//Select Project
const SELECT_PROJECT = 'SELECT_PROJECT';
//Reset Project
const RESET_PROJECT = 'RESET_PROJECT';
const RESET_SELECTED_PROJECT = 'RESET_SELECTED_PROJECT';

//Load all categories in project
const LOAD_ALL_CATEGORIES_IN_PROJECT = 'LOAD_ALL_CATEGORIES_IN_PROJECT';
const LOAD_ALL_CATEGORIES_IN_PROJECT_REQUEST = 'LOAD_ALL_CATEGORIES_IN_PROJECT_REQUEST';
const LOAD_ALL_CATEGORIES_IN_PROJECT_SUCCESS = 'LOAD_ALL_CATEGORIES_IN_PROJECT_SUCCESS';
const LOAD_ALL_CATEGORIES_IN_PROJECT_FAILURE = 'LOAD_ALL_CATEGORIES_IN_PROJECT_FAILURE';

//Load notification count
const LOAD_NOTIFICATION_COUNT = 'LOAD_NOTIFICATION_COUNT';
const LOAD_NOTIFICATION_COUNT_REQUEST = 'LOAD_NOTIFICATION_COUNT_REQUEST';
const LOAD_NOTIFICATION_COUNT_SUCCESS = 'LOAD_NOTIFICATION_COUNT_SUCCESS';
const LOAD_NOTIFICATION_COUNT_FAILURE = 'LOAD_NOTIFICATION_COUNT_FAILURE';

const RESET_NOTIFICATION_COUNT = 'RESET_NOTIFICATION_COUNT';

//Search
const SEARCH = 'SEARCH';
const SEARCH_REQUEST = 'SEARCH_REQUEST';
const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
const SEARCH_FAILURE = 'SEARCH_FAILURE';

//Reset all categories
const RESET_ALL_CATEGORIES = 'RESET_ALL_CATEGORIES';

export {
  LOAD_ALL_CATEGORIES_IN_PROJECT,
  LOAD_ALL_CATEGORIES_IN_PROJECT_REQUEST,
  LOAD_ALL_CATEGORIES_IN_PROJECT_SUCCESS,
  LOAD_ALL_CATEGORIES_IN_PROJECT_FAILURE,
  LOAD_CURRENT_USER,
  REQUEST_LOAD_CURRENT_USER,
  LOAD_CURRENT_USER_SUCCESS,
  LOAD_CURRENT_USER_FAILURE,
  UPDATE_CURRENT_USER_ROLE,
  OPEN_MODAL,
  CLOSE_MODAL,
  LOAD_PROJECT_DETAILS,
  LOAD_PROJECT_DETAILS_REQUEST,
  LOAD_PROJECT_DETAILS_SUCCESS,
  LOAD_PROJECT_DETAILS_FAILURE,
  SELECT_PROJECT,
  LOAD_NOTIFICATION_COUNT,
  LOAD_NOTIFICATION_COUNT_REQUEST,
  LOAD_NOTIFICATION_COUNT_SUCCESS,
  LOAD_NOTIFICATION_COUNT_FAILURE,
  SEARCH,
  SEARCH_REQUEST,
  SEARCH_SUCCESS,
  SEARCH_FAILURE,
  RESET_PROJECT,
  RESET_SELECTED_PROJECT,
  RESET_ALL_CATEGORIES,
  RESET_NOTIFICATION_COUNT,
  RESET_USER
}
