//Load User
const LOAD_CURRENT_USER = 'account/LOAD_CURRENT_USER';
const REQUEST_LOAD_CURRENT_USER = 'account/REQUEST_LOAD_CURRENT_USER';
const LOAD_CURRENT_USER_SUCCESS = 'account/LOAD_CURRENT_USER_SUCCESS';
const LOAD_CURRENT_USER_FAILURE = 'account/LOAD_CURRENT_USER_FAILURE';
//Update User Role
const UPDATE_CURRENT_USER_ROLE = 'UPDATE_CURRENT_USER_ROLE';
//Modal
const OPEN_MODAL = 'OPEN_MODAL';
const CLOSE_MODAL = 'CLOSE_MODAL';
//Load Project Details
const LOAD_PROJECT_DETAILS = 'LOAD_PROJECT_DETAILS';
const LOAD_PROJECT_DETAILS_REQUEST = 'LOAD_PROJECT_DETAILS_REQUEST';
const LOAD_PROJECT_DETAILS_SUCCESS = 'LOAD_PROJECT_DETAILS_SUCCESS';
const LOAD_PROJECT_DETAILS_FAILURE = 'LOAD_PROJECT_DETAILS_FAILURE';
//Select Project
const SELECT_PROJECT = 'SELECT_PROJECT';
//Reset Project
const RESET_PROJECT = 'RESET_PROJECT';

export {
  LOAD_CURRENT_USER,
  REQUEST_LOAD_CURRENT_USER,
  LOAD_CURRENT_USER_SUCCESS,
  LOAD_CURRENT_USER_FAILURE,
  UPDATE_CURRENT_USER_ROLE,
  OPEN_MODAL,
  CLOSE_MODAL,
  LOAD_PROJECT_DETAILS,
  LOAD_PROJECT_DETAILS_REQUEST,
  LOAD_PROJECT_DETAILS_SUCCESS,
  LOAD_PROJECT_DETAILS_FAILURE,
  SELECT_PROJECT,
  RESET_PROJECT
}
