//Load User
const LOAD_CURRENT_USER = 'account/LOAD_CURRENT_USER';
const REQUEST_LOAD_CURRENT_USER = 'account/REQUEST_LOAD_CURRENT_USER';
const LOAD_CURRENT_USER_SUCCESS = 'account/LOAD_CURRENT_USER_SUCCESS';
const LOAD_CURRENT_USER_FAILURE = 'account/LOAD_CURRENT_USER_FAILURE';
//Modal
const OPEN_MODAL = 'OPEN_MODAL';
const CLOSE_MODAL = 'CLOSE_MODAL';
//Project
const SELECT_PROJECT = 'SELECT_PROJECT';

const RESET_PROJECT = 'RESET_PROJECT';

export {
  LOAD_CURRENT_USER,
  REQUEST_LOAD_CURRENT_USER,
  LOAD_CURRENT_USER_SUCCESS,
  LOAD_CURRENT_USER_FAILURE,
  OPEN_MODAL,
  CLOSE_MODAL,
  SELECT_PROJECT,
  RESET_PROJECT
}
